echo ""
echo ==============================
echo CYCLE 1 INGESTION INSTRUCTIONS
echo ==============================
echo ""
echo "mkdir <DIR>"
echo ""
echo "mv <NAME>.tar <DIR>"
echo ""
echo "cd <DIR>"
echo ""
echo "diff_md5.sh <DIR>"
echo ""
echo "tarutil.py <NAME>.tar"
echo ""
echo "cycle1Tar.py <NAME>.tar"
echo ""
echo "data_ingest.py <NAME>.tar"
echo ""
echo "createquery.py <NAME>.tar"
echo ""
echo "sqlplus @ALMA"
echo ""
echo "Fill wiki https://adcwiki.alma.cl/bin/view/APO/APOIngestedProjects"
echo ""
echo "NOTE"
echo "===="
echo ""
echo "For an automatic ingestion go to created <DIR> and use:"
echo ""
echo "all_automatic.py <NAME>.tar" 	
echo ""
echo "and then when tars have arrived to ARCS run the sql obtained"
echo ""
